name: Cattaz
description: |
  Brings all of the activities of the team together at one place.
  Changes team's "Working Style", "Communication", "Motivation".
  It is an evolved Wiki that can launch, organize, accumulate and share knowledge freely using applications tailored to the activities of teams from Markdown.
version: Latest
category: Collaboration
