lb:
  image: rancher/load-balancer-service
  ports:
    - 3000
  links:
    - redmine:redmine
redmine:
  image: redmine:3.1
  environment:
    POSTGRES_PORT_5432_TCP: postgres
    POSTGRES_ENV_POSTGRES_USER: redmine
    POSTGRES_ENV_POSTGRES_PASSWORD: secret
    POSTGRES_ENV_POSTGRES_DB: redmine
  volumes:
    - redmine_data:/usr/src/redmine/files
  links:
    - "postgres:postgres"
postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: redmine
  volumes:
    - postgres_data:/var/lib/postgresql/data
